src/main.py

testing out comments in JIRA with multiple repos

KING-73 testing comments in JIRA

---

src/main_gabe.py

Testing adding gabe custom main repo

Adding gabe to repo

---

src/main_gabe.py

Added comments to gabe-main
Pleas apprv

Adding comments to gabe_main

---

src/kingscripts/operations/greasebook.py
src/main_gabe.py

KING-92 added working directory to allocations

---

src/kingscripts/afe/afe.py
src/main.py

adding combineAfe - testing with DaysVDepth

---

src/kingscripts/operations/joyn.py
src/main.py

KING-103 adding username/password to joyn script

---

src/kingscripts/operations/joyn.py
src/main.py

KING-106 adding millerranchc302mh to kingscripts

---

README.md

updating README.md and pushing v3.0.0 phase one

---

src/main_gabe.py

Please approve - from working session

KING-108 Updating Gabe to JOYN

---

src/kingscripts/operations/joyn.py
src/main.py

added break in joyn script

---

src/kingscripts/operations/joyn.py
src/main.py

look at me adding to the codebase

KING-109 got date rolling to work

---

src/kingscripts/operations/combocurve.py

some of my best work aka took from 1.5 years ago and slighty refactored

adding getLatestScenarioMonthly() and pushing to dev repo

---

src/kingscripts/operations/combocurve.py
src/main.py

DEV-113 cc to crest single well econonmics draft sent

---

src/kingscripts/analytics/tech.py
src/main.py

DEV-146 adding badPumperReport through KOC Datawarehouse 3.0

---

src/kingscripts/analytics/tech.py

DEV-156 updated getdata function for sql queries

---

src/gsql.py

Please review and approve at your earliest convenience.

DEV-157 created gabe python file for sql queries

---

src/kingscripts/afe/afe.py
src/main.py

pushing dvd curves to sql server - running in production

DEV-151 deployed dvd curve tables to SQL server

---

src/kingscripts/operations/joyn.py
src/main.py

DEV-162 fixing unknown status - due to missing JOYN ID

---

src/kingscripts/operations/joyn.py

DEV-168 adding ability to get different user id's

---

src/gsql.py

Michael, 
Adding some comments on how to pull req. 
Gabe

Testing pull request features

---

src/gsql.py

finished adding comments to gsql

---

src/gsql.py

Please approve thank you kind sir

Saved some changes to gsql.py

---

src/etl_joyn.py
src/kingscripts/analytics/tech.py
src/kingscripts/operations/joyn.py
src/main.py

DEV-172 getting the flattened json file

---

src/allFunctions.py
src/kingscripts/operations/combocurve.py
src/main.py

DEV-174 updating combocurve to joyn scripts

---

src/kingscripts/operations/combocurve.py
src/kingscripts/operations/joyn.py
src/main.py

DEV-174 updating joyn script to include uuid

---

src/gsql.py
src/kingscripts/operations/joyn.py

Made some changes to the headers of the SQL Server (added AssetID, removed comments and wellheader data)
Please review and approve, thanks!

Updated daily_production to remove wellheader data

---

src/etl_joyn.py
src/kingscripts/analytics/tech.py
src/kingscripts/operations/joyn.py

- Added Daily Well Reading refresh to ETL
- Explored re-configuring the delete records process in an attempt to improve runtime, legacy code worked faster but left attempt in the code base (commented out) to revisit in the future.

Added Daily Well Reading refresh to ETL

---

src/etl_combocurve.py
src/kingscripts/operations/combocurve.py
src/main.py

DEV-174 adding etl_combocurve and getting it running

---

src/etl_combocurve.py
src/etl_joyn.py
src/etl_scada.py
src/kingscripts/analytics/king.py
src/kingscripts/operations/joyn.py

rolling out usage stats

---

src/etl_scada.py
src/kingscripts/analytics/king.py
src/kingscripts/operations/combocurve.py
src/main.py

my goodnes we are good an quick

DEV-179 rolling out buffalo well into SCADA view

---

src/etl_scada.py
src/kingscripts/analytics/king.py
src/main.py

DEV-180 rolling out WU108 codebase for scada

---

src/etl_main.py
src/kingscripts/analytics/king.py

DEV-178 adding etl_main.py

---

README.md
src/etl_joyn.py

DEV-165 updating readme.md for go-live

---

src/kingscripts/operations/zdscada.py
src/main.py

DEV-181 getting zdcada up and running

---

src/etl_scada.py
src/kingscripts/analytics/king.py
src/main.py

DEV-183 rolling out conocophillips echo wells to etl_scada

---

src/daily_reporting.py
src/etl_scada.py
src/kingscripts/analytics/king.py
src/kingscripts/operations/reporting.py

Corrected column order for ECHO unit uploads and patched production data

---

src/kingscripts/analytics/tech.py
src/main.py

DEV-189 updating code to handle different authentication types
